### ISSUE TITLE
Support Audi Connect

### ISSUE THREAD

**Issue by AlCalzone** [RPerkuhn/ioBroker.vw-carnet#15]
I was just messing around with the Audi Connect API when I found this adapter. As it seems, both use the same API with some minor differences:

* The base part of the URL is `msg.audi.de` instead of `msg.volkswagen.de`.
* The initial `VWCarNet_Brand` is `"Audi"`.
* And some request headers are different:
    ```
    "X-App-ID": "de.audi.mmiapp",
	"X-App-Name": "MMIconnect",
	"X-App-Version": "2.8.3",
	"X-Brand": "audi",
    ```

If this is something you would like to support, I can provide a PR.

P.S.: Deutsch geht auch, ich bin nur gewöhnt auf GitHub englisch zu schreiben.

**Comment by TA2k** [comment]
integrated in vw connect adapter https://forum.iobroker.net/topic/26438/test-adapter-vw-connect-v0-0-x
