### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by Ridesa** [RPerkuhn/ioBroker.vw-carnet#2]
Hallo habe den Adapter installiert und die Zugangsdaten eingegeben aber ich bekomme beim Starten den Fehler

VSR.security.9007: The service: statusreport_v1 for VIN: WXXXXXXXXXXXXXXX could not be found.

**Comment by RPerkuhn** [comment]
Hallo, Voraussetzung für den Betrieb des Adapters ist ein aktiver Volkswagen "Security & Service Plus" Vertrag. Dieser wird bei Neuwagen kostenlos für ein Jahr gewährt. Danach ist er kostenpflichtig.
(das wusste ich zur ersten Version des Adapters auch noch nicht so genau - ab Version 0.2.0 wird das im Vorfeld geprüft)
